# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Id9s < Formula
  desc "Identity-nines — hybrid identity (AD on-prem, Entra ID) TUI at terminal speed, inspired by k9s"
  homepage "https://github.com/lazy-admins/id9s"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lazy-admins/id9s/releases/download/v0.4.0/id9s_darwin_amd64.tar.gz"
      sha256 "b90a7f0a9758c687149fffd8159672ce6c22320ce562d171405088a6deaf9a8d"

      define_method(:install) do
        bin.install "id9s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lazy-admins/id9s/releases/download/v0.4.0/id9s_darwin_arm64.tar.gz"
      sha256 "5a02110c5500bdd8f89258dc4cdbaf923359e8a3cb9663d64df160586d24bad9"

      define_method(:install) do
        bin.install "id9s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lazy-admins/id9s/releases/download/v0.4.0/id9s_linux_amd64.tar.gz"
      sha256 "4d39b768f9db1a2a057d1bd9455f9515dfac43cc61daa9e88af95552ce5d0c3d"
      define_method(:install) do
        bin.install "id9s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lazy-admins/id9s/releases/download/v0.4.0/id9s_linux_arm64.tar.gz"
      sha256 "91bafafdd29a307e0ac0cf214e9c60acedcf10437f4421d4a88dc3de1c910124"
      define_method(:install) do
        bin.install "id9s"
      end
    end
  end

  test do
    system "#{bin}/id9s", "--version"
  end
end
